# Generated by Django 4.2.2 on 2023-06-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_clientprofile_sellerprofile_client_seller"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("subttitle", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("main_image", models.ImageField(upload_to="eventImages/")),
                ("thumbnail", models.ImageField(upload_to="eventThumbnails/")),
                ("licence", models.FileField(upload_to="licences/")),
                ("address", models.CharField(max_length=128)),
                ("city", models.CharField(default="Marrakech", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_category",
                        to="shop.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Event_creator",
                        to="user.sellerprofile",
                    ),
                ),
            ],
            options={"verbose_name": "Event", "verbose_name_plural": "Events",},
        ),
        migrations.CreateModel(
            name="Pricing_plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_type", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "tickets_available",
                    models.IntegerField(default=1000, max_length=5000),
                ),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corresponding_event",
                        to="shop.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing_plan",
                "verbose_name_plural": "Pricing_plans",
            },
        ),
    ]
