# Generated by Django 4.2.2 on 2023-06-26 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_event_pricing_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing_plan",
            name="tickets_available",
            field=models.IntegerField(
                default=1000,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
