# Generated by Django 4.2.2 on 2023-06-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_pricing_plan_tickets_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
