# Generated by Django 4.2.2 on 2023-06-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_clientprofile_sellerprofile_client_seller"),
        ("shop", "0005_alter_organization_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Event_creator",
                to="user.seller",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Organisation_creator",
                to="user.seller",
            ),
        ),
    ]
