# Generated by Django 4.2.2 on 2023-06-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="role",),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
