# Generated by Django 4.2.2 on 2023-06-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_is_student_remove_user_is_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CLIENT", "Client"),
                    ("SELLER", "Seller"),
                ],
                max_length=50,
            ),
        ),
    ]
